use crate::parse_test;

parse_test!(ne "[iT4plex]-EM[Oxidation]EVNES[ES[Phospho]PEK[iTRAQ4plex]-[Methyl]", hang_01);
parse_test!(ne "[TRAQ4plex]-EM[ 
    iTRAQ4plex]-EM[ 
     ", hang_02);
parse_test!(ne "<< II0>", hang_03);
parse_test!(ne "[iTRAQFplex]-EM[Oxidation]EVNES[Phospho]PEKniTREMK[XLMOD:02000#XL1]]EVTKSET:02000#XL1E[XLMOD[XLMOD:02  򆼡", hang_04);
parse_test!(ne "iTRA[Formula:[  |||||||||||||||||||||]hZsqh|||||||    13C      ]E", hang_05);
parse_test!(ne "uHLC[Formula:[13C2][19C2]n12W-20]EO[avqrx|hNiwxy]E", hang_06);
parse_test!(ne "<5BE>[qTR(Qplex]-EM[Oxidation]EVNES[Phospho]EEEEEEEEEEEEEEEEELEEEEEEEEEEEEEMK[XLMOD:021]E+K", hang_07);
parse_test!(ne "[Formula:K13pUKOLM[0s|ho]DLM[0spho]]-", hang_08);
parse_test!(ne "[MOD:020110#EMEspho|O-phosL-serine|OCE//K[][]UENCE//K[]UENCE", hang_09);
parse_test!(ne "[U=hTRAQ4plex]-EM[U:Oxidation]EVNES[U:Phospho]PEK[U:iTRAQ4plex]-[U:Methyl]/3", hang_10);
parse_test!(ne "[L:iTRAQ4plex]-EM[U:Oxidation]EVNES[U:Phospho]PEK[U:iTRAQ4plex]-[U:Methyl]/3", hang_11);
parse_test!(ne "[U=iTRAQ4plex]-EM[U:Oxidation]EVNES[U:Phospho]PEK[U:iTRAQ4plex]-[U:Methyl]/3", hang_12);
parse_test!(ne "[ :iTROQ4plex]-EM[U::::::::::::::::/::::::EK[U:iTRAQ4plexd-[U::::::EK[U:iTRAQ4Methyl]/3", hang_13);
parse_test!(ne "[U TRAQ4plex]-EM[U:Oxidation]EVKpho]PEK[U:iTRAQ7zlex]-[U:Metx]-[U:Methyl]/3", hang_14);
parse_test!(ne "[:Oxidation]K[U:iplex]6dU:MethEVNES[]-EM[U:Oxidation]K[U:iplex]6dU:Methyl]/3", hang_15);
parse_test!(ne "plS[UQ4plex]-[U:Methyl]ex]-EM[U:Oxidation]EVNES[U:Phospho]PEK[U:iTRAQ4plex]-[U:Methyl]/3", hang_16);
parse_test!(ne "[V:iTRAQ4plex]-EM[UOxidation]EVNES[U>Phospho]PEK[U:iTRAQ4plex]-[U:Methyl]/3", hang_17);
parse_test!(ne "[ ;iTRAQ4plex]-Etiion]EVNES[U:Phthyl]/3", hang_18);
parse_test!(ne "[Uation]EVNES[U:i ospho]PEK[U@iTRAQ4plex]-U:Methyl]/3", hang_19);
parse_test!(ne "[URi:RAQ4plex]-EMM=MMn]EVNlex]-[oOho]PEK[U:iT2AQ4plex]-0U'Methyl]/3", hang_20);
parse_test!(ne "o[	:iTRAQ4Olex]-EM[U:Oxidatioj`DIWES[ K[U:i2[U:iTRAQU:Phospho]PE", hang_21);
parse_test!(ne "[e:iTRAQ<plex]-E:Ph ", hang_22);
parse_test!(ne "[dehyaio]^3?Q[gln->pyro-glu]SC", hang_23);
parse_test!(ne "[deidationhydro]^3?QRAidationo-glu]SC", hang_24);
parse_test!(ne "[dehyehydro]^3?Q[glC->pyro-", hang_25);
parse_test!(ne "  gldro]^3?Q[glC->pyro-glu]Sn", hang_26);
parse_test!(ne "[d))))))))))))))))))))))))ehydro]^3?Q[ghn-=pyro-gluISC", hang_27);
parse_test!(ne "MPGLVDSNPAPPESQEKKPLK(PCCACPETKKARDACIIEKGEEHCGHLIEAHKECMRALGFKI)[Oxdation]^2[half cystine][half cystine]", hang_28);
parse_test!(ne "MPGLVDSNPAPPESQEKKPLK(AHKECMRALGFKI)[Oxidation]^2[half cystine][half cystine]", hang_29);
parse_test!(ne "[dehydro]^6?Q[gln->pyro-gxSEK[XLMOD:02001#?L1[U:U:iTRAQ4plex]-EM[U:Oxidation]	 NiTRA[U:iTRlnWQ4plexgln->pyro-glu]Q4plex]-EM|UFOxidation]E", hang_30);
parse_test!(ne "xSEK[XLMOD:02011#XL1]UENCE//EMEVTK[XLMO:02009#XL1]SESPE", hang_31);
parse_test!(ne "SEQUEN[Formula:B13C2][12C-2]H2N]CE", hang_32);
parse_test!(ne "SEQUTN[Formula:u13C2][12C-2]H2N]CE", hang_33);
parse_test!(ne "SEQUEN[Fo-glu]SC>pyro-gl->pyro-glu]SC> NE				", hang_34);
parse_test!(ne "SEQUEN[Formula:C13C2][1 C-2]H2N]CE", hang_35);
parse_test!(ne "xSETK[xSEK[XLMOD:02001#?L1[U:U:iTRAQ4plex]-EM[U:Oxi   on]	 NiTRAQ4plex]-EM|U:Oxidation]EVNES[U@Phogpho]PEK[", hang_36);
parse_test!(ne "<[TMT2plex]@K,N-term>AWhDRNHA+NHA+[U*iTRAQ4plex]-EM[U:Oxidation]EVNES[U:Phos", hang_37);
parse_test!(ne "SEQWEN[Formula:[13C22N]CE][12C  2]H2N]CE", hang_38);
parse_test!(ne "[1][deh 1    1#XM1][deh 1#XM^3C- 1#XMXLMOD:D:#XM^3C-Q", hang_39);
parse_test!(ne "SEQUEN[Formula:[13C2C-2]H2NNNNNNNNNNNNNNN2][12C-2]H2NNNNNNNNNNNNNNNNN]CE", hang_40);
parse_test!(ne "SEQUEN[Formula:[13C2][12C-2]H2NNN2][12C-2]H2NNNNCE", hang_41);
parse_test!(ne "SEQUEN[Formula:[13C2][12C-2]H2NNNNNNNNNNNN13C2][12C-2]H2NNNNNNNN]CE", hang_42);
parse_test!(ne "SEQUEN[Formula:[13C2][12C-2]H213C2][12C-2]HNNNN]eE", hang_43);
parse_test!(ne "ex[ P:Met(yl]8S][U:O2C-ͨ", hang_44);
parse_test!(ne "SEQUEN[Formula:[05B2][12C2]H2NN0 |NNNNNNNNNNNNNN]CE", hang_45);
parse_test!(ne "SEQUEN[Formula:[16C2][12C-2]H2222][12C-2]22N:NNNNNhONNNNNN2222212:2222NNNNNNNhNNBNNNNNN]]", hang_46);
parse_test!(ne "NFJGDN[Formula:[13C2][12C-2]H2NNNcdrfffffffffffffffffffffffffffNNNNNYAMEVEAXFPKBYAVZBW  2010[C:[pldt]-[LD:i			 NES[thybfmwpxionngzzng[U:hVpl[U:Oxidatio|n]]]]]_][^", hang_47);
parse_test!(ne "[Glycan:HHHNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNPeNNNNGNPNN][U:|TRAQ4plex]-EM", hang_48);
parse_test!(ne "[Formula:C-2][XLMODmula:C-2][XLMODeh 1#XM^3C- 1#XM1][deh 1#XM^(C- ", hang_49);
parse_test!(ne "[12B-2]H2u¨", hang_50);
parse_test!(ne "NFJNNNNNNNN[Glycan:P0][    h][    h 1#XM^3#- 1# M1", hang_51);
parse_test!(ne "[dehydrotio]^<?Q[[1]]SEro dAA]^	 NE	 ", hang_52);
parse_test!(ne "[ͨH2>Z]uU:򆼡Kngthhhhhhhhhh@K,N-serm>Z", hang_53);
parse_test!(ne "[Glycan:HHHHHHHHHHHH0HHHHH0HHHHHNNNHNNNNNN2][12C-2]H22222NNNNNNNhNNNNNNN222222222222NNNNNNfNNHHHHHHH0HHHHH0HHHHHNNNNNNNNNNNNNfNNHHHHHHH0HHHHH0HHHHHNNNNN0]-T", hang_54);
parse_test!(ne "[Glycan:HHHHHTRIHHHH0HHHHH0HHHHHNNNHNNNNNNNfNNHHHHHHH0][12CL2]H2NNNNNENhNNNNHHFYFIFDPTDK/3NENMCHBJQCN[M:06101[C:[plex]-[UC:i			 NES[thydatiotionngting[U:iTRAQ%pl[U:Oxidation]EV  S[U:PhosphoEVEESPEex]-EM[U:O", hang_55);
parse_test!(ne "{Glycan:Hex}[iTRAQ4plex]-EV[Oovered|IRAQ4plex]-EV[Oovered|INFxidatNFxidation]EVNES[Phospho]PEK[iTRAQ4plex]-[Methylan:]", hang_56);
parse_test!(ne "[iTRAQ4plVx]-EM[O   tion]DVNESHP{M[Ox		hospho]PPPPEK[iTRAQ4plex]-[Met򆼠", hang_57);
parse_test!(ne "[Glycan:HexSHHHHH1HHTET][Hex][dehydro6plfx][Hex][deydro]^ESA", hang_58);
parse_test!(ne "[Glycan: ][Glyc   GS0][Glycan:{GlyexS0][G{GS0x]@K,N>ATQQQLTCNly", hang_59);
parse_test!(ne "[dehydro]^-5[Glycan:HexSHHHH1HH@E3333333fx][d   [de@exSHH^HH1HH@ET6H13333333fx][HexGG ][dehydro]^-2[Glycan:HexSHHHH1HH@E3333333fx][d   [dehydro]^-______________________________2\\H\\H", hang_60);
parse_test!(ne "[Formula:FMTcNu:PHRXRwW2ec|lmZzeqokjzkrTp]-", hang_61);
parse_test!(ne "[iTRAQ5glex]-EM[Oxidation]EVNES[Phospho]PEK[iTRAQ4plex]-[Methyl]", hang_62);
parse_test!(ne "[M:0ned|INMEVXLened|INMEV1V1]UE10		^n ?AA<<</<01#1001#XLened|INMEVXLened|INMEV1V1]UE[Formula:u1TanoYH2][rmula:[13C2][1C-2]H2-]-[Formula:uMTC339422][Coa:[][1I2N]CH+n01#XLMEV1][MOD:02001#XLMEV1]UnYH-]-[Glycan:HPEN1[MOD:020MEf1][MOD:02060#XLMEf1][MOD:02060#XLMEf1][MOD802060#X1][fLMEM:02060#XLMEf1][Formula:u1ESPEK/P[+2Na+,+[7987BR8N5822][Dye:[][0A-2]213#XL1]SMEVTK[XLMOD:02113#XL1]S[Glycan:HHHHHSSSSSSSSSSSSSSSSSSSSSSSSSSS9SSSSHSSSSSSSSSSSSSSSSSSSSSSSSSSS9SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS2][12C-23C2][12C-2]H222222222", hang_63);
